"""
faq_engine.py
─────────────
Pre-trained FAQ store with TF-IDF cosine-similarity retrieval.
  • Returns a canned answer when confidence > threshold → saves API calls.
  • Exposes a simple feedback loop: answers that users ✅ are boosted,
    answers that users ❌ are penalised → lightweight "self-learning".
"""

from __future__ import annotations

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# ══════════════════════════════════════════════════════════════
# FAQ KNOWLEDGE BASE
# ══════════════════════════════════════════════════════════════
_FAQ_DB: list[dict] = [
    # ── identity ──────────────────────────────────────────
    {
        "question": "What is your name? Who are you?",
        "answer":   "I'm **DynamiChat** 🤖 – a dynamic, AI-powered chatbot built with Google Gemini, NLP, and Machine Learning. I'm here to chat, help, and learn!",
        "score":    1.0,
    },
    {
        "question": "Are you a real person or a bot?",
        "answer":   "I'm an AI chatbot – not a real person. But I do my best to be helpful and have a natural conversation! 😊",
        "score":    1.0,
    },
    # ── capabilities ──────────────────────────────────────
    {
        "question": "What can you do? What are your features?",
        "answer":   (
            "Here's what I can do:\n"
            "• 💬 **Chat** – natural conversations on almost any topic\n"
            "• 🧠 **Intent Recognition** – I understand what you're asking\n"
            "• 🏷️  **Entity Extraction** – I spot emails, dates, cities, etc.\n"
            "• 😊 **Sentiment & Emotion Detection** – I sense how you feel\n"
            "• 📊 **Analytics Dashboard** – track our conversation stats\n"
            "• 🎯 **FAQ Answers** – instant replies for common questions\n"
            "• 🤖 **Self-Learning** – I improve based on your feedback!"
        ),
        "score":    1.0,
    },
    {
        "question": "Can you help me with coding or programming?",
        "answer":   "Absolutely! I can help with coding questions, debugging, explanations, and even writing code snippets. Just ask! 💻",
        "score":    1.0,
    },
    {
        "question": "Can you translate languages?",
        "answer":   "I can help with basic translations and language-related questions. For best results, tell me the source and target language! 🌍",
        "score":    1.0,
    },
    # ── how-it-works ──────────────────────────────────────
    {
        "question": "How does sentiment analysis work?",
        "answer":   (
            "I use a **TF-IDF + Logistic Regression** model trained on labelled data to classify your message as:\n"
            "• **Polarity**: positive / negative / neutral\n"
            "• **Emotion**: joy / anger / sadness / fear / surprise / neutral\n"
            "The results show up in the sidebar and influence how I respond!"
        ),
        "score":    1.0,
    },
    {
        "question": "How does intent recognition work?",
        "answer":   (
            "Intent recognition uses a **two-stage pipeline**:\n"
            "1. Fast regex pattern matching for common intents\n"
            "2. TF-IDF cosine-similarity fallback for paraphrases\n"
            "This lets me understand *what* you're asking even if you phrase it differently."
        ),
        "score":    1.0,
    },
    {
        "question": "What is Named Entity Recognition NER?",
        "answer":   "NER extracts important pieces of information from your text – like **emails**, **phone numbers**, **cities**, **dates**, **currencies**, and **names**. I highlight them in the sidebar! 🏷️",
        "score":    1.0,
    },
    {
        "question": "What AI model powers you?",
        "answer":   "My responses are generated by **Google Gemini** (gemini-2.0-flash by default). I also use scikit-learn models for sentiment, intent, and FAQ matching – all running locally! 🤖",
        "score":    1.0,
    },
    # ── usage ─────────────────────────────────────────────
    {
        "question": "How do I give feedback?",
        "answer":   "After each response you'll see 👍 and 👎 buttons. Tap them to tell me if my answer was helpful – it helps me improve! 🎯",
        "score":    1.0,
    },
    {
        "question": "How do I clear the conversation?",
        "answer":   "Click the **🗑️ Clear Chat** button in the sidebar to start a fresh conversation. Analytics history is kept unless you also clear that.",
        "score":    1.0,
    },
    {
        "question": "How do I see analytics?",
        "answer":   "Switch to the **📊 Analytics Dashboard** tab at the top of the page. It shows intent distribution, sentiment trends, response times, and more!",
        "score":    1.0,
    },
    # ── greetings ─────────────────────────────────────────
    {
        "question": "Hello hi hey good morning good evening",
        "answer":   "Hey there! 👋 Welcome to **DynamiChat**! How can I help you today? Feel free to ask me anything!",
        "score":    1.0,
    },
    # ── thanks ────────────────────────────────────────────
    {
        "question": "Thank you thanks appreciate",
        "answer":   "You're welcome! 😊 Happy to help. Let me know if there's anything else I can do for you!",
        "score":    1.0,
    },
    # ── jokes ─────────────────────────────────────────────
    {
        "question": "Tell me a joke funny",
        "answer":   "Why did the AI go to therapy? 🤖 Because it had too many **unresolved dependencies**! 😄",
        "score":    1.0,
    },
]


# ══════════════════════════════════════════════════════════════
# TF-IDF RETRIEVER
# ══════════════════════════════════════════════════════════════
class FAQEngine:
    CONFIDENCE_THRESHOLD = 0.28      # cosine sim above this → use FAQ answer

    def __init__(self) -> None:
        self._db        = list(_FAQ_DB)                 # mutable copy
        self._vectoriser = TfidfVectorizer(ngram_range=(1, 2), max_features=8000)
        self._rebuild_index()

    # ── public ────────────────────────────────────────────
    def query(self, text: str) -> tuple[str | None, float]:
        """
        Returns (answer, confidence).
        answer is None when confidence < threshold.
        """
        if not text or not text.strip():
            return None, 0.0

        q_vec  = self._vectoriser.transform([text])
        sims   = cosine_similarity(q_vec, self._q_vecs)[0]

        # weight by learned score (feedback loop)
        scores = np.array([item["score"] for item in self._db])
        weighted = sims * scores

        best_idx  = int(np.argmax(weighted))
        best_conf = float(weighted[best_idx])

        if best_conf >= self.CONFIDENCE_THRESHOLD:
            return self._db[best_idx]["answer"], round(best_conf, 3)
        return None, round(best_conf, 3)

    # ── feedback (self-learning) ──────────────────────────
    def feedback(self, text: str, positive: bool) -> None:
        """Boost or penalise the FAQ that matched the user's query."""
        if not text or not text.strip():
            return
        q_vec  = self._vectoriser.transform([text])
        sims   = cosine_similarity(q_vec, self._q_vecs)[0]
        best_idx = int(np.argmax(sims))

        if positive:
            self._db[best_idx]["score"] = min(self._db[best_idx]["score"] * 1.15, 3.0)
        else:
            self._db[best_idx]["score"] = max(self._db[best_idx]["score"] * 0.80, 0.1)

    # ── internal ──────────────────────────────────────────
    def _rebuild_index(self) -> None:
        questions = [item["question"] for item in self._db]
        self._q_vecs = self._vectoriser.fit_transform(questions)
